debian/@TMP@/@PF@/lib/*		@PF@/lib/
debian/@TMP@/@PF@/include/*	usr/include/

@BUILD@/Makefile.common		@PF@/build/
@BUILD@/Makefile.config		@PF@/build/
@BUILD@/config.status		@PF@/build/
Makefile.rules			@PF@/build/
configure			@PF@/build/
autoconf/			@PF@/build/

utils/vim/llvm-2.9.vim		usr/share/vim/addons/syntax/
utils/vim/tablegen-2.9.vim	usr/share/vim/addons/syntax/

utils/emacs/emacs.el		usr/share/emacs/site-lisp/llvm-2.9/
utils/emacs/llvm-mode.el	usr/share/emacs/site-lisp/llvm-2.9/
utils/emacs/tablegen-mode.el	usr/share/emacs/site-lisp/llvm-2.9/

