DEBIAN_TAR = llvm-toolchain-3.2_3.2repack-11.debian.tar.gz
ORIG_TARS  = llvm-toolchain-3.2_3.2repack.orig.tar.bz2
ORIG_TARS += llvm-toolchain-3.2_3.2repack.orig-clang.tar.bz2
ORIG_TARS += llvm-toolchain-3.2_3.2repack.orig-compiler-rt.tar.bz2
ORIG_TARS += llvm-toolchain-3.2_3.2repack.orig-lldb.tar.bz2
ORIG_TARS += llvm-toolchain-3.2_3.2repack.orig-polly.tar.bz2

include ../debian-orig.mk
