BASE_URL   = http://http.debian.net/debian/pool/main/l/llvm-toolchain-3.3
DEBIAN_TAR = llvm-toolchain-3.3_3.3-16.debian.tar.gz
ORIG_TARS  = llvm-toolchain-3.3_3.3.orig.tar.bz2
ORIG_TARS += llvm-toolchain-3.3_3.3.orig-clang.tar.bz2
ORIG_TARS += llvm-toolchain-3.3_3.3.orig-clang-tools-extra.tar.bz2
ORIG_TARS += llvm-toolchain-3.3_3.3.orig-compiler-rt.tar.bz2
ORIG_TARS += llvm-toolchain-3.3_3.3.orig-lldb.tar.bz2
ORIG_TARS += llvm-toolchain-3.3_3.3.orig-polly.tar.bz2

include ../debian-orig.mk
