DEBIAN_TAR = llvm-toolchain-3.6_3.6-2.debian.tar.xz
ORIG_TARS  = llvm-toolchain-3.6_3.6.orig.tar.bz2
ORIG_TARS += llvm-toolchain-3.6_3.6.orig-clang.tar.bz2
ORIG_TARS += llvm-toolchain-3.6_3.6.orig-clang-tools-extra.tar.bz2
ORIG_TARS += llvm-toolchain-3.6_3.6.orig-compiler-rt.tar.bz2
ORIG_TARS += llvm-toolchain-3.6_3.6.orig-lldb.tar.bz2
ORIG_TARS += llvm-toolchain-3.6_3.6.orig-polly.tar.bz2

include ../debian-orig.mk
