BASE_URL   = http://http.debian.net/debian/pool/main/l/llvm-toolchain-3.4
DEBIAN_TAR = llvm-toolchain-3.4_3.4.2-6.debian.tar.xz
ORIG_TARS  = llvm-toolchain-3.4_3.4.2.orig.tar.bz2
ORIG_TARS += llvm-toolchain-3.4_3.4.2.orig-clang.tar.bz2
ORIG_TARS += llvm-toolchain-3.4_3.4.2.orig-clang-tools-extra.tar.bz2
ORIG_TARS += llvm-toolchain-3.4_3.4.2.orig-compiler-rt.tar.bz2
ORIG_TARS += llvm-toolchain-3.4_3.4.2.orig-lldb.tar.bz2
ORIG_TARS += llvm-toolchain-3.4_3.4.2.orig-polly.tar.bz2

include ../debian-orig.mk
