DEBIAN_TAR = llvm-toolchain-3.5_3.5.2-5.debian.tar.xz
ORIG_TARS  = llvm-toolchain-3.5_3.5.2.orig.tar.bz2
ORIG_TARS += llvm-toolchain-3.5_3.5.2.orig-clang.tar.bz2
ORIG_TARS += llvm-toolchain-3.5_3.5.2.orig-clang-tools-extra.tar.bz2
ORIG_TARS += llvm-toolchain-3.5_3.5.2.orig-compiler-rt.tar.bz2
ORIG_TARS += llvm-toolchain-3.5_3.5.2.orig-lldb.tar.bz2
ORIG_TARS += llvm-toolchain-3.5_3.5.2.orig-polly.tar.bz2

include ../debian-orig.mk
