BASE_URL   = http://http.debian.net/debian/pool/main/l/llvm-toolchain-3.5
DEBIAN_TAR = llvm-toolchain-3.5_3.5-4.debian.tar.xz
ORIG_TARS  = llvm-toolchain-3.5_3.5.orig.tar.bz2
ORIG_TARS += llvm-toolchain-3.5_3.5.orig-clang.tar.bz2
ORIG_TARS += llvm-toolchain-3.5_3.5.orig-clang-tools-extra.tar.bz2
ORIG_TARS += llvm-toolchain-3.5_3.5.orig-compiler-rt.tar.bz2
ORIG_TARS += llvm-toolchain-3.5_3.5.orig-lldb.tar.bz2
ORIG_TARS += llvm-toolchain-3.5_3.5.orig-polly.tar.bz2

include ../debian-orig.mk
