usr/lib/llvm-3.2/bin/clang
usr/lib/llvm-3.2/bin/clang++
usr/lib/llvm-3.2/bin/clang-check
usr/lib/llvm-3.2/bin/clang-tblgen
usr/bin/clang-3.2
usr/bin/clang++-3.2
usr/bin/clang-check-3.2
usr/bin/clang-tblgen-3.2
tools/clang/tools/scan-build-3.2		usr/share/clang/
tools/clang/tools/scan-view-3.2			usr/share/clang/
#usr/share/man/man1/clang.1	usr/share/man/man1/
debian/pollycc					usr/lib/llvm-3.2/bin/
compiler-rt/lib/asan/scripts/asan_symbolize.py	usr/lib/llvm-3.2/bin/

