usr/lib/llvm-3.2/bin/clang			/usr/lib/llvm-3.2/bin/
usr/lib/llvm-3.2/bin/clang++			/usr/lib/llvm-3.2/bin/
usr/lib/llvm-3.2/bin/clang-check		/usr/lib/llvm-3.2/bin/
usr/lib/llvm-3.2/bin/clang-tblgen		/usr/lib/llvm-3.2/bin/
tools/clang/tools/scan-build			/usr/lib/llvm-3.2/share/
tools/clang/tools/scan-view			/usr/lib/llvm-3.2/share/
#usr/share/man/man1/clang.1	usr/share/man/man1/
debian/pollycc		/usr/lib/llvm-3.2/bin/

