BASE_URL   = https://launchpad.net/debian/experimental/+source/clang/1:3.2-1~exp9/+files
DEBIAN_TAR = clang_3.2-1~exp9.debian.tar.gz
ORIG_TARS  = clang_3.2.orig.tar.bz2
ORIG_TARS += clang_3.2.orig-compiler-rt.tar.bz2

include ../debian-orig.mk
